sudo: required
services:
 - docker
env:
 global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
#install Google Cloud SDK Cli
#configure SDK with our Google cloud auth info
 - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
 - curl https://sdk.cloud.google.com | bash > /dev/null;
 - source $HOME/google-cloud-sdk/path.bash.inc
 - gcloud components update kubectl
 - gcloud auth activate-service-account --key-file service-account.json
 - gcloud config set project multi-k8-235514
 - gcloud config set compute/zone europe-west6-c
 - gcloud container clusters get-credentials multi-cluster
 #login to docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 #build the "test"" version of mutli-client
 - docker build -t mityab/react-test -f ./client/Dockerfile.dev ./client

script:
#run tests
  - docker run mityab/react-test npm test -- --coverage
#if tests are succesfull deploy new images

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master

 
