apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-itadviser-by-tls
spec:
  secretName: k8s-itadviser-by
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.itadviser.by
  dnsNames:
    - k8s.itadviser.by
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.itadviser.by
